# Generated by Django 3.2.16 on 2023-01-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_auto_20230124_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='tag',
            new_name='tags',
        ),
    ]
