# Generated by Django 3.2.16 on 2023-01-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_rename_tag_women_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['id']},
        ),
    ]
