# Generated by Django 3.2.16 on 2023-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_tags_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
